### obtener todos los kinesiologos
GET http://localhost:3000/api/turnos/pacientes

###
GET http://localhost:3000/api/turnos/pacientes/da32350a-e479-495b-a5bc-82466deb1538


###
POST http://localhost:3000/api/turnos/pacientes
Content-Type: application/json

{
    "nombre": "Enzo",
    "apellido":"Manavella",
    "dni":"45906709",
    "fechaNacimiento":"11/10/2003",
    "obraSocial":"Swiss Medical",
    "telefono": "341339088",
    "email":"enzomanavella@gmail.com",
    "password":"contaseña",
    "estado":"activo"
}


###
PUT http://localhost:3000/api/turnos/pacientes/da32350a-e479-495b-a5bc-82466deb1538
Content-Type: application/json

{
    "nombre": "Facundo",
    "apellido":"Morresi",
    "dni":"45864009",
    "fechaNacimiento":"24/11/2003",
    "obraSocial":"Swiss Medical",
    "telefono": "3329339061",
    "email":"facum@gmail.com",
    "password":"facumorresi",
    "estado":"activo"
    
}


###
DELETE http://localhost:3000/api/turnos/pacientes/458f0caa-34cf-45f5-a863-d2da6d82b94e