### obtener todos los tunros
GET http://localhost:3000/api/turnos

### obtener un tunro
GET http://localhost:3000/api/turnos/6699b0bdd6a40b3980b1a048

### crear un nuevo tunro
POST http://localhost:3000/api/turnos
Content-Type: application/json

{
    "fecha": "20-09-2024",
    "hora": "18:30",
    "estado": "Activo",
    "importeTotal": 4500
}

### modificar un tunro PUT
PUT http://localhost:3000/api/turnos/6698453b55c972c8d0c4e49e
Content-Type: application/json

{
    "fecha": "27-09-2024",
    "hora": "18:30",
    "estado": "Activo",
    "importeTotal": 4500
}

### modificar un tunro PATCH
PATCH http://localhost:3000/api/turnos/6698453b55c972c8d0c4e49e
Content-Type: application/json

{
    "estado": "Completo",
}

### borrar un tunro
DELETE http://localhost:3000/api/turnos/6699b0bdd6a40b3980b1a048