### obtener todos los kinesiologos
GET http://localhost:3000/api/kinesiologos


### crear un nuevo kinesiologo
# @name createKinesiologo
POST http://localhost:3000/api/kinesiologos
Content-Type: application/json

{
    "matricula":"AB500",
    "nombre": "Ramiro",
    "apellido": "Parisi",
    "mail": "ramaparisi264@gmail.com",
    "password": "aRospej241",
    "telefono": 341333444 ,
    "dni": 44291893,
    "especialidad": 1,
    "consultorio": 1
}

### POST a kinesiologo
POST http://localhost:3000/api/kinesiologos
Content-Type: application/json

{

    "matricula":"AB600",
    "nombre": "Enzo",
    "apellido": "Manavella",
    "mail": "emanavella@gmail.com",
    "password": "veNatuEr423",
    "telefono": 341888999 ,
    "dni": 44291893,
    "especialidad": 2,
    "consultorio": 2
}


### ID
@id = {{createKinesiologo.response.body.data.id}}

### GET one kinesiologo
http://localhost:3000/api/kinesiologos/{{id}}


### PUT a kinesiologo
PUT http://localhost:3000/api/kinesiologos/{{id}}
Content-Type: application/json

{
    "consultorio": 4
}



### POST a kinesiologo
# @name createKinesiologoToDelete
POST http://localhost:3000/api/kinesiologos
Content-Type: application/json

{
    "matricula":"AB700",
    "nombre": "Facundo",
    "apellido": "Morresi",
    "mail": "facumorresi21@gmail.com",
    "password": "sanPeDRO534",
    "telefono": 341777111 ,
    "dni": 43491793,
    "especialidad": 2,
    "consultorio": 1
}


### DELETE a character
@idToDelete = {{createKinesiologoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/kinesiologos/{{idToDelete}}


### PATCH a character
PATCH http://localhost:3000/api/kinesiologos/{{idToDelete}}
Content-Type: application/json

{
  "telefono": 4578730
}

### DELETE a character
DELETE http://localhost:3000/api/kinesiologos/{{idToDelete}}