### GET ALL
GET http://localhost:3000/api/tiposDeAtencion

### POST
# @name createTipoAtencion
POST http://localhost:3000/api/tiposDeAtencion
Content-Type: application/json

{
    "nombre": "Osteopatia",
    "estado": true
}


### POST 2
POST http://localhost:3000/api/tiposDeAtencion
Content-Type: application/json

{
    "nombre": "Rehabilitación",
    "estado": true
}


###ID
@id = {{createTipoAtencion.response.body.data.id}}


### GET ONE
GET http://localhost:3000/api/tiposDeAtencion/{{id}}



### PUT
PUT http://localhost:3000/api/tiposDeAtencion/{{id}}
Content-Type: application/json

{
    "estado": false
}


### POST CHARACTER TO DELETE
# @name createTipoAtencionToDelete
POST http://localhost:3000/api/tiposDeAtencion
Content-Type: application/json

{
    "nombre": "Estética",
    "estado": true
}

### DELETE
@idToDelete = {{createTipoAtencionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/TiposDeAtencion/{{idToDelete}}