### obtener todos los characters
GET http://localhost:3000/api/secretarias


### obtener un character
GET http://localhost:3000/api/secretarias/66983f41730259abeafec790

### crear un nuevo character
POST http://localhost:3000/api/secretarias
Content-Type: application/json

{
  "nombre": "Cintia",
  "apellido": "Farruggio",
  "mail": "moap_cvf@hotmail.com",
  "contraseña": "GGpeugeot",
  "telefono": 341250734,
  "dni": 12345678
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/secretarias/66983f41730259abeafec790
Content-Type: application/json

{
  "nombre": "Sofia",
  "apellido": "Ortellado",
  "mail": "sofortellado@hotmail.com",
  "contraseña": "namelessking",
  "telefono": 3413248386,
  "dni": 42270984    
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/secretarias/66983f41730259abeafec790
Content-Type: application/json

{
  "nombre": "Sofia",
  "apellido": "Ortellado",
  "telefono": 341333777   
}

### borrar un character
DELETE http://localhost:3000/api/secretarias/66983f41730259abeafec790