### GET ALL
GET http://localhost:3000/api/tiposDeAtencion/precios

### POST
# @name createPrecio
POST http://localhost:3000/api/tiposDeAtencion/precios
Content-Type: application/json

{
    "fechaDesde": "20240619",
    "importe": "5000"
}


### POST 2
POST http://localhost:3000/api/tiposDeAtencion/precios
Content-Type: application/json

{
    "fechaDesde": "20240619",
    "importe": "4000"
}


###ID
@id = {{createPrecio.response.body.data.id}}


### GET ONE
GET http://localhost:3000/api/tiposDeAtencion/precios/{{id}}



### PUT
PUT http://localhost:3000/api/tiposDeAtencion/precios/{{id}}
Content-Type: application/json

{
    "fechaDesde": "20240819",
    "importe": "6000"
}


### POST CHARACTER TO DELETE
# @name createPrecioToDelete
POST http://localhost:3000/api/tiposDeAtencion/precios
Content-Type: application/json

{
    "fechaDesde": "202409109",
    "importe": "9000"
}

### DELETE
@idToDelete = {{createPrecioToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/TiposDeAtencion/precios/{{idToDelete}}