### obtener todos los characters
GET http://localhost:3000/api/secretarias


### crear un nuevo character
# @name createSecretaria
POST http://localhost:3000/api/secretarias
Content-Type: application/json

{
  "nombre": "Cintia",
  "apellido": "Farruggio",
  "email": "moap_cvf@hotmail.com",
  "password": "GGpeugeot77",
  "telefono": 341250734,
  "dni": 12345678,
  "consultorio": 1
}

### POST a character
POST http://localhost:3000/api/secretarias
Content-Type: application/json

{
  "nombre": "Sofia",
  "apellido": "Ortellado",
  "email": "sof.ortellado25@gmail.com",
  "password": "namelessking",
  "telefono": 341777888,
  "dni": 87654321,
  "consultorio": 2
}


### ID
@id = {{createSecretaria.response.body.data.id}}

### GET one character
http://localhost:3000/api/secretarias/{{id}}


### PUT a character
PUT http://localhost:3000/api/secretarias/{{id}}
Content-Type: application/json

{
  "nombre": "Padme",
  "apellido": "Amidala",
  "email": "padneamidala@hotmail.com",
  "password": "Radahan",
  "dni": 42270984,
  "consultorio": 2,
  "telefono": 341777888
}



### POST a character to Delete
# @name createSecretariaToDelete
POST http://localhost:3000/api/secretarias
Content-Type: application/json

{
    "nombre": "Ashoka",
    "apellido": "Tano",
    "email": "ashoka@gmail.com",
    "password": "greenGdsfffG543SAa",
    "telefono": 562381291,
    "dni": 11111111,
    "consultorio": 1
}


### DELETE a character
@idToDelete = {{createSecretariaToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/secretarias/{{idToDelete}}


### PATCH a character
PATCH http://localhost:3000/api/secretarias/{{idToDelete}}
Content-Type: application/json

{
  "consultorio": 2
}

### DELETE a character
DELETE http://localhost:3000/api/secretarias/{{idToDelete}}