GET http://localhost:3000/api/pacientes

###
GET http://localhost:3000/api/pacientes/a1ea6381-dfd8-4a95-a930-ac45c02a2a9c


###
POST http://localhost:3000/api/pacientes
Content-Type: application/json

{
    "nombre": "Enzo",
    "apellido":"Manavella",
    "dni":"45906709",
    "fechaNacimiento":"11/10/2003",
    "obraSocial":"Swiss Medical",
    "telefono": "341339088",
    "email":"enzomanavella@gmail.com",
    "password":"contaseña",
    "estado":"activo"
}


###
PUT http://localhost:3000/api/pacientes/a1ea6381-dfd8-4a95-a930-ac45c02a2a9c
Content-Type: application/json

{
    "nombre": "Facundo",
    "apellido":"Morresi",
    "dni":"45864009",
    "fechaNacimiento":"24/11/2003",
    "obraSocial":"Swiss Medical",
    "telefono": "3329339061",
    "email":"facum@gmail.com",
    "password":"facumorresi",
    "estado":"activo"
    
}


###
DELETE http://localhost:3000/api/pacientes/6a097479-b958-4011-a4e9-4208e864e6d4