### GET ALL
GET http://localhost:3000/api/secretarias/consultorios

### POST
# @name createConsultorio
POST http://localhost:3000/api/secretarias/consultorios
Content-Type: application/json

{
    "nombre": "Musculitoo",
    "domicilio": "Sanchez de loria 77777"
}


### POST 2
POST http://localhost:3000/api/secretarias/consultorios
Content-Type: application/json

{
    "nombre": "KineSport",
    "domicilio": "Juan Jose Paso 1500"
}


###ID
@id = {{createConsultorio.response.body.data.id}}


### GET ONE
GET http://localhost:3000/api/secretarias/consultorios/{{id}}



### PUT
PUT http://localhost:3000/api/secretarias/consultorios/{{id}}
Content-Type: application/json

{
    "nombre": "Musculito",
    "domicilio": "Pitagoras 777"
}


### POST CHARACTER TO DELETE
# @name createConsultorioToDelete
POST http://localhost:3000/api/secretarias/consultorios
Content-Type: application/json

{
    "nombre": "Kinesport",
    "domicilio": "Juan Jose Paso 1578"
}

### DELETE
@idToDelete = {{createConsultorioToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/secretarias/consultorios/{{idToDelete}}